[build]
  command = "npm run build" # Or "yarn build" if you use yarn
  publish = "dist" # Your Vite build output directory

[functions]
  directory = "netlify/functions" # Tells Netlify where to find your serverless functions
  node_bundler = "esbuild" # Recommended for faster builds
  # external_node_modules = ["resend"] # Optional: If you encounter issues with large dependencies

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200